FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:stable-alpine AS production

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

#EXPOSE 5173
#CMD ["npm", "run", "dev"]
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

